name: ETL Automation

on: workflow_dispatch


jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: region eu-north-1


      - name:  Run Glue crawler to create table / schema
        run: aws glue start-crawler --name json_data_crawler
      
      - name: Create AWS Glue Crawler
        run: aws glue create-crawler 
        --name "${{ github.event.inputs.crawlerName }}" --role your-glue-service-role --database-name your-database-name --targets '{ "S3Targets": [{ "Path": "s3://your-s3-bucket" }] }'

      - name: Execute Glue Notebook to flatten json
        run: aws glue start-notebook-execution --notebook-name MyNotebookName
      
      - name: Run Glue Crawlers to generate table (flatenned data and paritions)
        run: aws glue start-crawler --name parquet_Table_gen