name: Image Security Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.45.1

    # - name: Get Latest Trivy Release URL
    #   id: get_latest_release
    #   run: |
    #     latest_release_url=$(curl -s -L -o /dev/null -w %{url_effective} "https://github.com/aquasecurity/trivy/releases/latest")
    #     echo "::set-output name=latest_release_url::$latest_release_url"
    #   shell: bash

    # - name: Download Trivy
    #   run: |
    #     download_url="${{ steps.get_latest_release.outputs.latest_release_url }}/trivy_linux_amd64"
    #     curl -sL -o /usr/local/bin/trivy "$download_url"
    #     chmod +x /usr/local/bin/trivy
    #     trivy --version
    #   shell: bash

    - name: List of Images
      run: |
        # Define the list of image names you want to scan
        images=("alpine:latest" "nginx:latest" "ubuntu:latest" "python:latest" "redis:latest" "postgres:latest" "node:latest" "httpd:latest" "memcached:latest" "mongo:latest" "mysql:latest" "traefik:latest" "mariadb:latest" "docker:latest" "rabbitmq:latest" "golang:latest" "wordpress:latest" "php:latest" "consul:latest" "sonarqube:latest" "ruby:latest" "haproxy:latest" "elasticsearch:latest" "tomcat:latest" "kong:latest" "neo4j:latest")

        for image in "${images[@]}"; do
          echo "Scanning $image"
          trivy --exit-code 0 --severity HIGH,CRITICAL --no-progress "$image"
        done
      shell: bash

    - name: Save Trivy Reports
      run: |
        mkdir -p trivy-reports
        mv /root/.cache/trivy/db/* trivy-reports/
      shell: bash

    - name: Upload Trivy Reports
      uses: actions/upload-artifact@v2
      with:
        name: trivy-reports
        path: trivy-reports

# name: Image Security Pipeline

# on:
#   push:
#     branches:
#       - main  # Adjust the branch as needed

# jobs:
#   scan:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     # - name: Trivy Scan
#     #   uses: aquasecurity/trivy-action@master
#     #   with:
#     #     image-ref: "alpine:latest,nginx:latest,ubuntu:latest,python:latest,redis:latest,postgres:latest,node:latest,httpd:latest,memcached:latest,mongo:latest,mysql:latest,traefik:latest,mariadb:latest,docker:latest,rabbitmq:latest,golang:latest,wordpress:latest,php:latest,consul:latest,sonarqube:latest,ruby:latest,haproxy:latest,elasticsearch:latest,tomcat:latest,kong:latest,neo4j:latest"

#     - name: Trivy Scan
#       uses: aquasecurity/trivy-action@master
#       with:
#         image-ref: >
#           alpine:latest
#           nginx:latest
#           ubuntu:latest
#           python:latest
#           redis:latest
#           postgres:latest
#           node:latest
#           httpd:latest
#           memcached:latest
#           mongo:latest
#           mysql:latest
#           traefik:latest
#           mariadb:latest
#           docker:latest
#           rabbitmq:latest
#           golang:latest
#           wordpress:latest
#           php:latest
#           consul:latest
#           sonarqube:latest
#           ruby:latest
#           haproxy:latest
#           elasticsearch:latest
#           tomcat:latest
#           kong:latest
#           neo4j:latest

#     - name: Save Trivy Reports
#       run: |
#         mkdir -p trivy-reports
#         mv -t trivy-reports /root/.cache/trivy/db/*
#       shell: bash

#     - name: Upload Trivy Reports
#       uses: actions/upload-artifact@v2
#       with:
#         name: trivy-reports
#         path: trivy-reports

#     # - name: Get Latest Trivy Release URL
#     #   id: get_latest_release
#     #   run: |
#     #     latest_release_url=$(curl -s -L -o /dev/null -w %{url_effective} "https://github.com/aquasecurity/trivy/releases/latest")
#     #     echo "::set-output name=latest_release_url::$latest_release_url"
#     #   shell: bash

#     # - name: Download Trivy
#     #   run: |
#     #     download_url="${{ steps.get_latest_release.outputs.latest_release_url }}/trivy_linux_amd64"
#     #     curl -sL -o /usr/local/bin/trivy "$download_url"
#     #     chmod +x /usr/local/bin/trivy
#     #     trivy --version
#     #   shell: bash

#     # - name: Get Latest Trivy Release URL
#     #   id: get_latest_release
#     #   run: |
#     #     latest_release_url=$(curl -s -L -o /dev/null -w %{url_effective} "https://github.com/aquasecurity/trivy/releases/latest")
#     #     echo "::set-output name=latest_release_url::$latest_release_url"
#     #   shell: bash

#     # - name: Download Trivy
#     #   run: |
#     #     download_url="${{ steps.get_latest_release.outputs.latest_release_url }}/download/trivy_linux_amd64.tar.gz"
#     #     curl -sL -o trivy.tar.gz "$download_url"
#     #     tar xvf trivy.tar.gz
#     #     chmod +x trivy
#     #     sudo mv trivy /usr/local/bin/trivy
#     #     trivy --version
#     #   shell: bash

#     # - name: List of Images
#     #   run: |
#     #     # Define the list of image names you want to scan
#     #     images=("alpine:latest" "nginx:latest" "ubuntu:latest" "python:latest" "redis:latest" "postgres:latest" "node:latest" "httpd:latest" "memcached:latest" "mongo:latest" "mysql:latest" "traefik:latest" "mariadb:latest" "docker:latest" "rabbitmq:latest" "golang:latest" "wordpress:latest" "php:latest" "consul:latest" "sonarqube:latest" "ruby:latest" "haproxy:latest" "elasticsearch:latest" "tomcat:latest" "kong:latest" "neo4j:latest")
    
#     #     for image in "${images[@]}"; do
#     #       echo "Pulling $image"
#     #       docker pull $image
    
#     #       echo "Scanning $image"
#     #       /usr/local/bin/trivy --exit-code 0 --severity HIGH,CRITICAL --no-progress $image
#     #     done
#     #   shell: bash

#     # - name: Save Trivy Reports
#     #   run: |
#     #     mkdir -p trivy-reports
#     #     mv -t trivy-reports /root/.cache/trivy/db/*
#     #   shell: bash

#     # - name: Upload Trivy Reports
#     #   uses: actions/upload-artifact@v2
#     #   with:
#     #     name: trivy-reports
#     #     path: trivy-reports